// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testMsgPackage.proto
// Protobuf C++ Version: 6.32.1

#ifndef testMsgPackage_2eproto_2epb_2eh
#define testMsgPackage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_testMsgPackage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_testMsgPackage_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_testMsgPackage_2eproto;
}  // extern "C"
class TestMsgPackage;
struct TestMsgPackageDefaultTypeInternal;
extern TestMsgPackageDefaultTypeInternal _TestMsgPackage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestMsgPackage_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class TestMsgPackage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TestMsgPackage) */ {
 public:
  inline TestMsgPackage() : TestMsgPackage(nullptr) {}
  ~TestMsgPackage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestMsgPackage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestMsgPackage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestMsgPackage(::google::protobuf::internal::ConstantInitialized);

  inline TestMsgPackage(const TestMsgPackage& from) : TestMsgPackage(nullptr, from) {}
  inline TestMsgPackage(TestMsgPackage&& from) noexcept
      : TestMsgPackage(nullptr, ::std::move(from)) {}
  inline TestMsgPackage& operator=(const TestMsgPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMsgPackage& operator=(TestMsgPackage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestMsgPackage& default_instance() {
    return *reinterpret_cast<const TestMsgPackage*>(
        &_TestMsgPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TestMsgPackage& a, TestMsgPackage& b) { a.Swap(&b); }
  inline void Swap(TestMsgPackage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMsgPackage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestMsgPackage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TestMsgPackage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestMsgPackage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestMsgPackage& from) { TestMsgPackage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TestMsgPackage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TestMsgPackage"; }

 protected:
  explicit TestMsgPackage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestMsgPackage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestMsgPackage& from);
  TestMsgPackage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestMsgPackage&& from) noexcept
      : TestMsgPackage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgNameFieldNumber = 2,
    kMsgIdFieldNumber = 1,
  };
  // string MsgName = 2;
  void clear_msgname() ;
  const ::std::string& msgname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_msgname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_msgname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_msgname();
  void set_allocated_msgname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_msgname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_msgname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_msgname();

  public:
  // int32 MsgId = 1;
  void clear_msgid() ;
  ::int32_t msgid() const;
  void set_msgid(::int32_t value);

  private:
  ::int32_t _internal_msgid() const;
  void _internal_set_msgid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:TestMsgPackage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 30,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestMsgPackage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr msgname_;
    ::int32_t msgid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_testMsgPackage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestMsgPackage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TestMsgPackage

// int32 MsgId = 1;
inline void TestMsgPackage::clear_msgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::int32_t TestMsgPackage::msgid() const {
  // @@protoc_insertion_point(field_get:TestMsgPackage.MsgId)
  return _internal_msgid();
}
inline void TestMsgPackage::set_msgid(::int32_t value) {
  _internal_set_msgid(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:TestMsgPackage.MsgId)
}
inline ::int32_t TestMsgPackage::_internal_msgid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msgid_;
}
inline void TestMsgPackage::_internal_set_msgid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgid_ = value;
}

// string MsgName = 2;
inline void TestMsgPackage::clear_msgname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& TestMsgPackage::msgname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TestMsgPackage.MsgName)
  return _internal_msgname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TestMsgPackage::set_msgname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.msgname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:TestMsgPackage.MsgName)
}
inline ::std::string* PROTOBUF_NONNULL TestMsgPackage::mutable_msgname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_msgname();
  // @@protoc_insertion_point(field_mutable:TestMsgPackage.MsgName)
  return _s;
}
inline const ::std::string& TestMsgPackage::_internal_msgname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msgname_.Get();
}
inline void TestMsgPackage::_internal_set_msgname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.msgname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TestMsgPackage::_internal_mutable_msgname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.msgname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TestMsgPackage::release_msgname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:TestMsgPackage.MsgName)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.msgname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.msgname_.Set("", GetArena());
  }
  return released;
}
inline void TestMsgPackage::set_allocated_msgname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.msgname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msgname_.IsDefault()) {
    _impl_.msgname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:TestMsgPackage.MsgName)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // testMsgPackage_2eproto_2epb_2eh
