// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testMsgPackage.proto
// Protobuf C++ Version: 6.32.1

#include "testMsgPackage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr TestMsgPackage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        msgname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TestMsgPackage::TestMsgPackage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TestMsgPackage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TestMsgPackageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestMsgPackageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMsgPackageDefaultTypeInternal() {}
  union {
    TestMsgPackage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMsgPackageDefaultTypeInternal _TestMsgPackage_default_instance_;
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_testMsgPackage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_testMsgPackage_2eproto = nullptr;
const ::uint32_t
    TableStruct_testMsgPackage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::TestMsgPackage, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::TestMsgPackage, _impl_.msgid_),
        PROTOBUF_FIELD_OFFSET(::TestMsgPackage, _impl_.msgname_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::TestMsgPackage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_TestMsgPackage_default_instance_._instance,
};
const char descriptor_table_protodef_testMsgPackage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024testMsgPackage.proto\"0\n\016TestMsgPackage"
    "\022\r\n\005MsgId\030\001 \001(\005\022\017\n\007MsgName\030\002 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_testMsgPackage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_testMsgPackage_2eproto = {
    false,
    false,
    80,
    descriptor_table_protodef_testMsgPackage_2eproto,
    "testMsgPackage.proto",
    &descriptor_table_testMsgPackage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_testMsgPackage_2eproto::offsets,
    file_level_enum_descriptors_testMsgPackage_2eproto,
    file_level_service_descriptors_testMsgPackage_2eproto,
};
// ===================================================================

class TestMsgPackage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TestMsgPackage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TestMsgPackage, _impl_._has_bits_);
};

TestMsgPackage::TestMsgPackage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsgPackage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TestMsgPackage)
}
PROTOBUF_NDEBUG_INLINE TestMsgPackage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::TestMsgPackage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        msgname_(arena, from.msgname_) {}

TestMsgPackage::TestMsgPackage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TestMsgPackage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsgPackage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestMsgPackage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.msgid_ = from._impl_.msgid_;

  // @@protoc_insertion_point(copy_constructor:TestMsgPackage)
}
PROTOBUF_NDEBUG_INLINE TestMsgPackage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        msgname_(arena) {}

inline void TestMsgPackage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.msgid_ = {};
}
TestMsgPackage::~TestMsgPackage() {
  // @@protoc_insertion_point(destructor:TestMsgPackage)
  SharedDtor(*this);
}
inline void TestMsgPackage::SharedDtor(MessageLite& self) {
  TestMsgPackage& this_ = static_cast<TestMsgPackage&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msgname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TestMsgPackage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TestMsgPackage(arena);
}
constexpr auto TestMsgPackage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TestMsgPackage),
                                            alignof(TestMsgPackage));
}
constexpr auto TestMsgPackage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TestMsgPackage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TestMsgPackage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TestMsgPackage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TestMsgPackage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TestMsgPackage>(), &TestMsgPackage::ByteSizeLong,
              &TestMsgPackage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TestMsgPackage, _impl_._cached_size_),
          false,
      },
      &TestMsgPackage::kDescriptorMethods,
      &descriptor_table_testMsgPackage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TestMsgPackage_class_data_ =
        TestMsgPackage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TestMsgPackage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TestMsgPackage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TestMsgPackage_class_data_.tc_table);
  return TestMsgPackage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2>
TestMsgPackage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestMsgPackage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TestMsgPackage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TestMsgPackage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string MsgName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(TestMsgPackage, _impl_.msgname_)}},
    // int32 MsgId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsgPackage, _impl_.msgid_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(TestMsgPackage, _impl_.msgid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 MsgId = 1;
    {PROTOBUF_FIELD_OFFSET(TestMsgPackage, _impl_.msgid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string MsgName = 2;
    {PROTOBUF_FIELD_OFFSET(TestMsgPackage, _impl_.msgname_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\7\0\0\0\0\0"
    "TestMsgPackage"
    "MsgName"
  }},
};
PROTOBUF_NOINLINE void TestMsgPackage::Clear() {
// @@protoc_insertion_point(message_clear_start:TestMsgPackage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.msgname_.ClearNonDefaultToEmpty();
  }
  _impl_.msgid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TestMsgPackage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TestMsgPackage& this_ = static_cast<const TestMsgPackage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TestMsgPackage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TestMsgPackage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:TestMsgPackage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 MsgId = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_msgid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_msgid(), target);
    }
  }

  // string MsgName = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_msgname().empty()) {
      const ::std::string& _s = this_._internal_msgname();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TestMsgPackage.MsgName");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TestMsgPackage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TestMsgPackage::ByteSizeLong(const MessageLite& base) {
  const TestMsgPackage& this_ = static_cast<const TestMsgPackage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TestMsgPackage::ByteSizeLong() const {
  const TestMsgPackage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:TestMsgPackage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // string MsgName = 2;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_msgname().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_msgname());
      }
    }
    // int32 MsgId = 1;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_msgid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_msgid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TestMsgPackage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TestMsgPackage*>(&to_msg);
  auto& from = static_cast<const TestMsgPackage&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:TestMsgPackage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_msgname().empty()) {
        _this->_internal_set_msgname(from._internal_msgname());
      } else {
        if (_this->_impl_.msgname_.IsDefault()) {
          _this->_internal_set_msgname("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_msgid() != 0) {
        _this->_impl_.msgid_ = from._impl_.msgid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestMsgPackage::CopyFrom(const TestMsgPackage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestMsgPackage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestMsgPackage::InternalSwap(TestMsgPackage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msgname_, &other->_impl_.msgname_, arena);
  swap(_impl_.msgid_, other->_impl_.msgid_);
}

::google::protobuf::Metadata TestMsgPackage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_testMsgPackage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
